### ISSUE TITLE
What license to use for this repository?

### ISSUE THREAD

**Issue by dhimmel** [greenelab/library-access#3]
I initially applied a CC0 License to this repository in https://github.com/greenelab/library-access/commit/4af802d4e94fd4ed25e87450f8c4fc1b86237e71, since I reckoned this will be primarily a data repository.

@publicus notes however:

> The [Onboarding documentation](http://greenelab-onboarding.readthedocs.io/en/latest/index.html) notes that the default code license of the lab is the 3-clause BSD. That's actually the license that I prefer for most of my work, and is one that I'd have a preference toward over the CC0 you included in the repo. Did you intend the CC0 to cover everything in the repo. (not just data, but also code)? If so, is there a funding agency requiring this, and if not, would you be comfortable with me using a BSD 3-clause on the code I'm writing?

Yes CC0 currently applies to everything in the repo. We have several options if you'd like a BSD license on some or all of the content:

1. Dual license everything as CC0 and BSD 3-Clause as we did in https://github.com/cognoma/cancer-data/pull/33
2. License everything as BSD 3-Clause and a subset of the files (the datasets) as CC0. This is similar to what we did [for Manubot](https://github.com/greenelab/manubot-rootstock/tree/72189b5bdff80573e0d89f7c2d30975753a57b2e#license) (but with CC BY and CC0)
3. Specify files as either BSD or CC0, but not both.

In general, I like CC0 because it becomes hard to distinguish what's code and what's data, and I don't find copyright has any utility in these contexts. In addition, as a study on Sci-Hub, it's symbolically powerful to forgo copyright under the premise that our creations are entirely free.

@publicus what do you prefer about BSD 3-Clause? I'm flexible here. We should update the licensing to whatever we decide before merging any other pull requests, and then proceed.

**Comment by jglev** [comment]
@dhimmel, I like the point you made about the symbolic use of a CC0 dedication for this project specifically. I agree with that, but also think that the symbolism applies if we use a permissive (or even copyleft, though we're not discussing that here) license -- in the same way that with even "Gold" open-access materials, the author[^1] maintains copyright but is still presenting the work for open, public re-use.

I like the BSD 3-Clause specifically because of that third clause; in general, it helps me focus more on writing code and making it public by helping to worry less about one type of public discourse that might come from the code. That type of discourse might not come up from this particular project, but I still like using the license for that contingency. I also like how permissive licenses like the BSD 3-Clause make code available for wide re-use while also making the provenance / history of that code available.

I particularly find your second suggested option (code: BSD 3-Clause, data: CC0) appealing for this case.

[^1]: (Hopefully, or the publisher)

**Comment by dhimmel** [comment]
> I like the BSD 3-Clause specifically because of that third clause

For reference this is:

> 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

Personally, I'm not too concerned about people redistributing modified versions of my code and than claiming that I endorse it... but I respect your concern.

> I particularly find your second suggested option (code: BSD 3-Clause, data: CC0) appealing for this case.

The second suggestion applies BSD to everything. And then dual licenses the code as CC0. For clarification, this is what you prefer?

So the CC0-exclusions to start with would be any file matching the glob `*.py`? Also `*.md`? And `*.r` if we add it?

You want to submit a PR or want me to?

**Comment by jglev** [comment]
Ah, my mistake -- what you suggested ("applies BSD to everything. And then dual licenses the code as CC0") also is fine with me, but I meant licensing code as BSD 3-Clause, and data as CC0, without any dual-licensing. I'll submit a PR for the latter in just a moment, and we can discuss it more if necessary from there.

And, the extensions you proposed for CC0-exclusions look correct to me.
